FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Script de espera para DB y RabbitMQ
COPY ./scripts/wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

EXPOSE 50051

CMD ["/wait-for-it.sh", "--", "/wait-for-it.sh", "rabbitmq:5672", "--", "npm", "run", "start"]
